### ISSUE TITLE
Script is not working?

### ISSUE THREAD

**Issue by mxxcon** [OSM-de/osm-org-greasemonkey#11]
I'm using Chrome stable with Tampermonkey 4.16.1

I'm not sure if I'm not seeing the right things or what, but I feel like this script is not working...
After installing and enabling it, the only difference I see are 2 extra buttons next to Export on top and that's it.
And even those buttons seem to randomly disappear on page refresh.

Tampermonkey shows that the script is enabled and running while I'm on https://www.openstreetmap.org/history

**Comment by kmpoppe** [comment]
Hi @mxxcon, nice to see you again.
So, I've not tested the script with Tampermonkey, mostly due to my ignorance of it existing, so might have some hickups.
The two buttons next to edit are supposed to appear instantly on page load/refresh, yet, sometimes that screws up and they appear after you move the map.
This has been an issue which I thought I had fixed, but I've recently seen it back in Firefox as well.

Please also try moving the map when you have a CS or any object open and see if the detaila overlay on the left gets links added to them.

K

**Comment by mxxcon** [comment]
This is what I see even after moving the map around
![image](https://user-images.githubusercontent.com/847140/187017599-35a07f0f-07c4-46ef-8050-ee5c43eb91bb.png)

And upon refreshing the page even those buttons are gone
![image](https://user-images.githubusercontent.com/847140/187017625-a8e9999f-079d-4b47-84eb-13608400a2b7.png)

**Comment by kmpoppe** [comment]
Please open a changeset (that'll show OsmCha link) or a node/way/relation/note so that it shows the full details, that should yield some links under the title

**Comment by mxxcon** [comment]
When I open changeset I see this
![image](https://user-images.githubusercontent.com/847140/187051786-778d51df-e4c8-4bd6-8eae-b14edba4964e.png)
Also when I open details of a way or node I don't see anything different other than 2 buttons on top.

**Comment by joshinils** [comment]
> When I open changeset I see this [image]
> Also when I open details of a way or node I don't see anything different other than 2 buttons on top.

What happens when you move the map around?
Does a link to OSMCha appear?
![image](https://user-images.githubusercontent.com/34302971/187051875-1aedabc3-58ad-40ce-8951-2043c8ff723c.png)


and on a way:
![image](https://user-images.githubusercontent.com/34302971/187051901-5b09fa57-acf9-4e3a-86ba-2dfe560e04db.png) 
move map -> 
![image](https://user-images.githubusercontent.com/34302971/187051912-299e6fe8-5795-4ef7-9982-52d456f70ddd.png)

so yeah, I still have the issue of links not appearing until I move the map

**Comment by mxxcon** [comment]
> What happens when you move the map around? Does a link to OSMCha appear?

Oh, ya, when I move the map those links do show up.

**Comment by mxxcon** [comment]
Seeing how it works I have 3 suggestions:
1) If possible make your links show up w/o having to move the map
2) Show osmcha links directly on changeset list (https://www.openstreetmap.org/history/) to make reviewing changesets faster.
3) Update README.md with a screenshots so that people can see what exactly this script adds.

**Comment by kmpoppe** [comment]
As I said, 1 was supposed to happen either way and in Firefox+GM it ~~does~~ (did at some point in time), so this is something we need to check against Chrome+TM as well.

2 and 3 will be treated as new enhancements.

**Comment by kmpoppe** [comment]
Replaced by #12, #13, #15
